### ISSUE TITLE
Error: Something went wrong

### ISSUE THREAD

**Issue by Ragziesoft** [MMRIZE/MMM-OpenAI#3]
Firstly, it is a great module, very simple and easy to implement. Well everything went right for me and the module was up and running in no time. However, it keeps  popping up the message " Something went wrong, see the log" quite frequently. After probably a few minutes it resumes chats but then again pops out the error. Is it because of high traffic of ChatGPT ? How to resolve this? And where are the logs?

**Comment by eouia** [comment]
I’m not sure. I’ll provide the modified version which will produce more friendly and easy error messages in a few days.

**Comment by eouia** [comment]
Check the new update. (#4)

**Comment by Ragziesoft** [comment]
Thanks it works okay now.
